<?php

namespace backend\controllers;

use backend\searchModels\EmployesSearch;
use yii\filters\AccessControl;

class HomeController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $this->layout="app";
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ],
                'denyCallback' => function ($r, $c) {
                    \Yii::$app->session->setFlash('danger',"Siz ro'yhatdan o'tmadiz");
                    \Yii::$app->user->loginRequired();
                }
            ]
        ];// TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new EmployesSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

}
