<?php

namespace frontend\controllers;

use yii\filters\AccessControl;

class HomeController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $this->layout = "app";
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {

        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ],
                'denyCallback' => function ($r, $a) {
                    \Yii::$app->session->setFlash("danger", "Tizimga kirish uchun ro'yhatdan o'tishiz kerak");
                    \Yii::$app->user->loginRequired();
                }
            ]
        ]; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

}
